---
version: 2
builds:
  - id: ceph-chaos-monkey
    main: ./cmd/ceph-chaos-monkey
    binary: ceph-chaos-monkey
    ldflags:
      - -s -w -X main.appVersion={{.Version}} -X main.buildTimestamp={{.Date}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
archives:
  - formats:
      - binary
checksum:
  name_template: "checksums.txt"
  algorithm: sha256
  split: false
  disable: false
release:
  prerelease: auto
